### ISSUE TITLE
Release build set to x64 on purpose?

### ISSUE THREAD

**Issue by jdkang** [piranout/Funcular.IdGenerators#2]
Is the release build set to x64 on purpose? The debug build is set to "any CPU".

Is there some kind of intent here? This causes some annoying issues as most applications are 32-bit.

**Comment by piranout** [comment]
Thanks for bringing this to my attention; pure oversight on my part. I'll patch the project file in the next few days.

**Comment by piranout** [comment]
@jdkang , I've updated all build configurations to "Any CPU" and pushed the changes. Thanks.
