### ISSUE TITLE
Multiple generators causing inconsistant outputs?

### ISSUE THREAD

**Issue by legendz3** [piranout/Funcular.IdGenerators#4]
For some reason the following test is failing: 
```
var generator = new Base36IdGenerator(
                numTimestampCharacters: 12,
                numServerCharacters: 6,
                numRandomCharacters: 7);
            
var shortGenerator = new Base36IdGenerator(
              numTimestampCharacters: 3,
              numServerCharacters: 0,
              numRandomCharacters: 12);
            var id1 = generator.NewId();
            var id2 = shortGenerator.NewId();
            Assert.AreEqual(25, id1.Length);
            Assert.AreEqual(15, id2.Length);
```

The second generator by itself will produce a 15 characters id, but when used in the same method as the first one will produce a 21 characters id.

**Comment by piranout** [comment]
Thanks for alerting me to this, Ke Zhu. I must have made the segment lengths static when they should have been instance fields. I will fix this in the next release.

**Comment by piranout** [comment]
Thanks again; this has been fixed in commit 4291c025. I will push the updates to the NuGet repo sometime this week.

**Comment by legendz3** [comment]
Hi, any updates on when the nuget package will be published? Thanks!

**Comment by piranout** [comment]
I literally just published it. It hasn't been indexed yet as of this moment, but the new version is 2.6, and I can see it at https://www.nuget.org/packages/Funcular.IdGenerators/2.6.0. Cheers!
