### ISSUE TITLE
JS compatible library recommendation.

### ISSUE THREAD

**Issue by lucasfolino** [piranout/Funcular.IdGenerators#5]
Do you know of any JS libraries that emulate or is compatible with this library.  I like the ids generated better than GUIDs, but need to generate a bunch of IDs on a front end and don't want to make a call to the server.  I could either batch generate a bunch of them to make them available and throw the rest away, or implement something myself in JS.

**Comment by piranout** [comment]
That's a great idea. I don't know of a JS library with this built in, but I do take pull requests if you end up implementing it. (If you do, just add a 'js' directory to the project and put it there. I'll add it to the next NuGet package next time I publish that as well.)
